name: hinflow
channels:
  # for channel compatibility issues, try run:
  # conda config --set channel_priority flexible
  # micromamba config set channel_priority flexible
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - cmake=3.30.3
  - easydict=1.9
  - einops=0.8.0
  - environs=11.0.0
  - future=1.0.0
  - gdown=5.2.0
  - h5py=3.9.0
  - hdf5=1.14.2
  - huggingface_hub=0.25.1
  - imageio=2.35.1
  - imageio-ffmpeg=0.5.1
  - json5=0.9.25
  - lightning=2.4.0
  - lightning-utilities=0.11.7
  - lit=19.1.0
  - llvm-openmp=15.0.7
  - llvmlite=0.43.0
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mediapy=1.2.2
  - moviepy=1.0.3
  - natsort=8.4.0
  - ninja=1.12.1
  - numba=0.60.0
  - numpy=1.24.4
  - pandas=2.2.3
  - pip=24.3.1
  - pynput=1.7.7
  - python=3.10.14
  - pytorch::pytorch==2.4.0
  - pytorch::pytorch-cuda>=12.1
  - pytorch::torchaudio==2.4.0
  - pytorch::torchvision==0.19.0
  - pytorch-lightning=2.4.0
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - scipy=1.14.1
  - setuptools=65.5.0
  - tensorboard=2.17.1
  - tensorboard-data-server=0.7.0
  - termcolor=2.4.0
  - timm=1.0.9
  - tqdm=4.66.5
  - wandb=0.17.3
  - wheel=0.38.4
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - bddl==1.0.1
      - cloudpickle==1.6.0
      - deepspeed==0.15.1
      - egl-probe==1.0.2
      - glfw==2.7.0
      - gym==0.22.0
      - gymnasium==0.29.1
      - hydra-core==1.3.2
      - line-profiler==4.1.1
      - mujoco==2.3.7
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - pybullet-svl==3.1.6.4
      - scikit-learn==1.5.2
      - tensordict==0.5.0
      - torchrl==0.5.0
      - flow-vis==0.1